export const questions = [
    { question: "If you could be a character in any movie, who would you be?", category: "Fun" },
    { question: "What’s your go-to karaoke song?", category: "Fun" },
    { question: "If you could live in any fictional world, which one would it be?", category: "Fun" },
    { question: "What’s the funniest thing that’s ever happened to you?", category: "Fun" },
    { question: "If you could only eat one food for the rest of your life, what would it be?", category: "Fun" },
    { question: "What’s your guilty pleasure TV show?", category: "Fun" },
    { question: "If animals could talk, which one would be the rudest?", category: "Weird" },
    { question: "If you could only speak in movie quotes, which movie would you choose?", category: "Fun" },
    { question: "What’s the weirdest food combination you’ve ever tried?", category: "Weird" },
    { question: "If you could have dinner with any fictional character, who would it be?", category: "Fun" },
    { question: "If you could be any animal for a day, which one would you be?", category: "Fun" },
    { question: "Would you rather fight one horse-sized duck or a hundred duck-sized horses?", category: "Weird" },
    { question: "If you could shrink down to the size of a pencil and live in someone’s pocket, whose pocket would you choose?", category: "Weird" },
    { question: "What’s the weirdest thing you’ve Googled?", category: "Weird" },
    { question: "Would you rather have fingers for toes or toes for fingers?", category: "Weird" },
    { question: "If you could turn any object into a pet, what would it be?", category: "Weird" },
    { question: "What’s your spirit animal?", category: "Fun" },
    { question: "If you could instantly learn any skill, what would it be?", category: "Fun" },
    { question: "What’s the strangest thing you’ve Googled?", category: "Weird" },
    { question: "Would you rather have a pet dragon or a pet unicorn?", category: "Fun" },
    { question: "What’s the weirdest place you’ve fallen asleep?", category: "Weird" },
    { question: "If you could only wear one color for the rest of your life, what would it be?", category: "Fun" },
    { question: "Would you rather have fingers for toes or toes for fingers?", category: "Weird" },
    { question: "If you could switch lives with any historical figure for a day, who would it be?", category: "Fun" },
    { question: "What would you do if you were invisible for a day?", category: "Weird" },
    { question: "If you could only eat one color of food for the rest of your life, which color would you choose?", category: "Fun" },
    { question: "Would you rather always have to hop like a kangaroo or slither like a snake?", category: "Weird" },
    { question: "If you could switch places with any famous person for a day, who would it be?", category: "Fun" },
    { question: "What’s the weirdest thing you’ve ever done for money?", category: "Weird" },
    { question: "If you could live without sleep, what would you do with all your extra time?", category: "Fun" },
    { question: "If you had to wear one outfit for the rest of your life, what would it be?", category: "Fun" },
    { question: "What’s the weirdest thing you’ve ever done on a dare?", category: "Weird" },
    { question: "If you could only have one superpower, what would it be?", category: "Fun" },
    { question: "What’s the oddest thing you’ve ever collected?", category: "Weird" },
    { question: "Would you rather be able to talk to plants or inanimate objects?", category: "Weird" },
    { question: "If you could only communicate with one type of animal for the rest of your life, which one would you choose?", category: "Weird" },
    { question: "Would you rather live in a house shaped like a shoe or a house shaped like a pineapple?", category: "Weird" },
    { question: "If you could have any mythical creature as a pet, what would it be?", category: "Fun" },
    { question: "What’s your go-to dance move when no one’s watching?", category: "Fun" },
    { question: "Would you rather fight a hundred tiny aliens or one giant alien?", category: "Weird" },
    { question: "If you could make any object come to life, what would you choose?", category: "Weird" },
    { question: "What’s the most bizarre dream you’ve ever had?", category: "Weird" },
    { question: "If you could only eat food shaped like one thing for the rest of your life, what would it be?", category: "Fun" },
    { question: "Would you rather have a hamster-sized elephant or an elephant-sized hamster?", category: "Weird" },
    { question: "If you could create a new color, what would it look like?", category: "Weird" },
    { question: "Would you rather be a giant or a tiny person?", category: "Weird" },
    { question: "What’s the weirdest thing you’ve ever heard someone say?", category: "Weird" },
    { question: "If you could have any animal feature, what would it be?", category: "Fun" },
    { question: "Would you rather live in a world where everyone can read your mind or a world where you can read everyone’s mind?", category: "Weird" },
    { question: "If you could create your own holiday, what would it be called and how would people celebrate?", category: "Fun" },
    { question: "Would you rather have a nose that grows every time you lie or ears that get bigger every time you’re embarrassed?", category: "Weird" },
    { question: "What’s the strangest thing you’ve ever found under your bed?", category: "Weird" },
    { question: "Would you rather always be dressed as a superhero or always be dressed as a villain?", category: "Fun" },
    { question: "What’s the most bizarre thing you’ve ever seen at a party?", category: "Weird" },
    { question: "If you could turn into any object, what would you choose?", category: "Weird" },
    { question: "Would you rather have to wear the same outfit every day or have no wardrobe at all?", category: "Weird" },
    { question: "If you could talk to one inanimate object for a day, which object would you choose?", category: "Weird" },
    { question: "What’s the most ridiculous fear you have?", category: "Weird" },
    { question: "Would you rather only be able to text or only be able to call people?", category: "Weird" },
    { question: "If you could create a new sport, what would it be like?", category: "Fun" },
    { question: "Would you rather only be able to walk backward or only be able to run sideways?", category: "Weird" },
    { question: "If you could live forever, would you?", category: "Fun" },
    { question: "Would you rather always have a tiny voice or a really deep voice?", category: "Weird" },
    { question: "If you could become a cartoon character, who would you choose to be?", category: "Fun" },
    { question: "Would you rather always be dressed as a superhero or always be dressed as a villain?", category: "Fun" },
    { question: "What’s the most bizarre thing you’ve ever heard someone say?", category: "Weird" },
    { question: "Would you rather be able to talk to animals or read minds?", category: "Weird" },
    { question: "If you could turn anything into a snack, what would it be?", category: "Weird" },
    { question: "What’s the weirdest thing you’ve ever eaten?", category: "Weird" },
    { question: "Would you rather live on a boat or in a treehouse?", category: "Fun" },
    { question: "If you could be famous for one thing, what would it be?", category: "Fun" },
    { question: "Would you rather have a personal robot or a personal jetpack?", category: "Fun" },
    { question: "What’s the oddest thing you’ve seen someone do?", category: "Weird" },
    { question: "Would you rather be able to teleport but always arrive with your shoes off, or never be able to teleport but have perfectly matched shoes?", category: "Weird" },
    { question: "What’s the most random thing you’ve bought and still own?", category: "Fun" },
    { question: "Would you rather be always 5 minutes early or always 10 minutes late?", category: "Fun" },
    { question: "What’s the weirdest item you’ve found in your pocket?", category: "Weird" },
    { question: "Would you rather have the ability to change your hair color at will or your eye color?", category: "Weird" },
    { question: "If you could switch brains with someone for a day, who would it be?", category: "Fun" },
    { question: "What’s the weirdest thing you’ve ever seen in public?", category: "Weird" },
    { question: "If you could turn into any object, what would you choose?", category: "Weird" },
    { question: "Would you rather have to wear the same outfit every day or have no wardrobe at all?", category: "Weird" },
        { question: "What’s your favorite hobby?", category: "Icebreaker" },
        { question: "If you could live anywhere in the world, where would it be?", category: "Icebreaker" },
        { question: "What’s the most unusual job you’ve ever had?", category: "Icebreaker" },
        { question: "What’s your favorite season and why?", category: "Icebreaker" },
        { question: "What’s your go-to karaoke song?", category: "Icebreaker" },
        { question: "If you could have any animal as a pet, what would it be?", category: "Icebreaker" },
        { question: "What’s your favorite book and why?", category: "Icebreaker" },
        { question: "If you were a superhero, what would your superpowers be?", category: "Icebreaker" },
        { question: "What’s the most adventurous thing you’ve ever done?", category: "Icebreaker" },
        { question: "What’s something you’ve always wanted to learn?", category: "Icebreaker" },
        { question: "If you could have dinner with any famous person, who would it be?", category: "Icebreaker" },
        { question: "If you could instantly become an expert in something, what would it be?", category: "Icebreaker" },
        { question: "What’s your favorite way to spend a day off?", category: "Icebreaker" },
        { question: "If you could switch lives with anyone for a day, who would it be?", category: "Icebreaker" },
        { question: "What’s the best vacation you’ve ever had?", category: "Icebreaker" },
        { question: "What’s your favorite childhood memory?", category: "Icebreaker" },
        { question: "If you could time travel, where and when would you go?", category: "Icebreaker" },
        { question: "What’s the weirdest food you’ve ever tried?", category: "Icebreaker" },
        { question: "If you could live in any fictional universe, which one would it be?", category: "Icebreaker" },
        { question: "What’s your dream job?", category: "Icebreaker" },
        { question: "What’s the last movie you watched?", category: "Icebreaker" },
        { question: "What’s one thing on your bucket list?", category: "Icebreaker" },
        { question: "What’s your favorite ice cream flavor?", category: "Icebreaker" },
        { question: "What’s the most interesting place you’ve visited?", category: "Icebreaker" },
        { question: "What’s your favorite board game or card game?", category: "Icebreaker" },
        { question: "If you could have any type of pet, what would it be?", category: "Icebreaker" },
        { question: "If you had to eat only one cuisine for the rest of your life, what would it be?", category: "Icebreaker" },
        { question: "What’s the funniest thing that’s happened to you recently?", category: "Icebreaker" },
        { question: "Do you believe in ghosts?", category: "Icebreaker" },
        { question: "If you could have a dinner party with any three people, who would you invite?", category: "Icebreaker" },
        { question: "What’s something you’ve done that you’re really proud of?", category: "Icebreaker" },
        { question: "If you were to win the lottery tomorrow, what’s the first thing you would buy?", category: "Icebreaker" },
        { question: "What’s the best gift you’ve ever received?", category: "Icebreaker" },
        { question: "What’s your most unusual talent?", category: "Icebreaker" },
        { question: "What’s the best piece of advice you’ve ever received?", category: "Icebreaker" },
        { question: "What’s your favorite holiday and why?", category: "Icebreaker" },
        { question: "If you could visit any place in the world, where would it be?", category: "Icebreaker" },
        { question: "If you could master any skill instantly, what would it be?", category: "Icebreaker" },
        { question: "What’s the craziest thing you’ve ever done for love?", category: "Icebreaker" },
        { question: "If you could only watch one TV show for the rest of your life, what would it be?", category: "Icebreaker" },
        { question: "If you had to change your name, what would you change it to?", category: "Icebreaker" },
        { question: "What’s your guilty pleasure?", category: "Icebreaker" },
        { question: "What’s the last book you read?", category: "Icebreaker" },
        { question: "What’s one food you can’t live without?", category: "Icebreaker" },
        { question: "If you could be any age for a week, what age would that be?", category: "Icebreaker" },
        { question: "What’s the most embarrassing thing you’ve done?", category: "Icebreaker" },
        { question: "If you could be famous for one thing, what would it be?", category: "Icebreaker" },
        { question: "What’s your most prized possession?", category: "Icebreaker" },
        { question: "What’s the worst haircut you’ve ever had?", category: "Icebreaker" },
        { question: "What’s something you would love to learn?", category: "Icebreaker" },
        { question: "What’s the best concert you’ve ever been to?", category: "Icebreaker" },
        { question: "If you could live in any time period, when would it be?", category: "Icebreaker" },
        { question: "What’s your biggest fear?", category: "Icebreaker" },
        { question: "What’s your favorite type of music?", category: "Icebreaker" },
        { question: "If you could have any car, what would it be?", category: "Icebreaker" },
        { question: "If you could be any character from a movie or TV show, who would it be?", category: "Icebreaker" },
        { question: "What’s your favorite sport?", category: "Icebreaker" },
        { question: "What’s your idea of a perfect day?", category: "Icebreaker" },
        { question: "What’s the funniest thing you’ve seen on the internet?", category: "Icebreaker" },
        { question: "If you could speak any language fluently, what would it be?", category: "Icebreaker" },
        { question: "What’s your favorite family tradition?", category: "Icebreaker" },
        { question: "What’s the best meal you’ve ever had?", category: "Icebreaker" },
        { question: "If you could be a professional athlete, what sport would you play?", category: "Icebreaker" },
        { question: "What’s your favorite childhood cartoon?", category: "Icebreaker" },
        { question: "What’s your favorite kind of weather?", category: "Icebreaker" },
        { question: "If you could create your own holiday, what would it be?", category: "Icebreaker" },
        { question: "What’s your dream vacation destination?", category: "Icebreaker" },
        { question: "If you could donate a million dollars to any cause, what would it be?", category: "Icebreaker" },
        { question: "What’s your favorite way to exercise?", category: "Icebreaker" },
        { question: "What’s the last thing you do before bed?", category: "Icebreaker" },
        { question: "What’s something you’ve done that you thought you would never do?", category: "Icebreaker" },
        { question: "What’s your favorite way to relax?", category: "Icebreaker" },
        { question: "What’s your favorite movie of all time?", category: "Icebreaker" },
        { question: "What’s something you want to accomplish this year?", category: "Icebreaker" },
        { question: "What’s the best advice you could give to someone?", category: "Icebreaker" },
        { question: "What’s the most ridiculous thing you’ve ever done?", category: "Icebreaker" },
        { question: "If you could meet any historical figure, who would it be?", category: "Icebreaker" },
        { question: "What’s the most memorable thing that’s ever happened to you?", category: "Icebreaker" },
        { question: "If you had a time machine, would you go forward or backward in time?", category: "Icebreaker" },
        { question: "What’s the best piece of advice you could give your younger self?", category: "Icebreaker" },
        { question: "What’s your favorite family recipe?", category: "Icebreaker" },
        { question: "What’s your go-to comfort food?", category: "Icebreaker" },
        { question: "If you could be an expert in anything, what would it be?", category: "Icebreaker" },
        { question: "What’s the most random fact you know?", category: "Icebreaker" },
        { question: "What’s your favorite holiday tradition?", category: "Icebreaker" },
        { question: "What’s the best compliment you’ve ever received?", category: "Icebreaker" },
        { question: "If you could master any instrument, what would it be?", category: "Icebreaker" },
        { question: "What’s your favorite guilty pleasure TV show?", category: "Icebreaker" },
        { question: "What’s one thing on your bucket list?", category: "Icebreaker" },
            { question: "Would you rather have the ability to fly or be invisible?", category: "Would You Rather" },
            { question: "Would you rather always have to sing instead of speak or dance everywhere you go?", category: "Would You Rather" },
            { question: "Would you rather be able to breathe underwater or have the ability to speak to animals?", category: "Would You Rather" },
            { question: "Would you rather time travel to the past or the future?", category: "Would You Rather" },
            { question: "Would you rather live in a world without pizza or without ice cream?", category: "Would You Rather" },
            { question: "Would you rather fight one horse-sized duck or a hundred duck-sized horses?", category: "Would You Rather" },
            { question: "Would you rather always be 10 minutes late or 20 minutes early?", category: "Would You Rather" },
            { question: "Would you rather be able to talk to machines or read minds?", category: "Would You Rather" },
            { question: "Would you rather live without social media or without TV?", category: "Would You Rather" },
            { question: "Would you rather have unlimited money but no friends, or lots of friends but barely any money?", category: "Would You Rather" },
            { question: "Would you rather visit space or explore the ocean?", category: "Would You Rather" },
            { question: "Would you rather be able to eat anything without gaining weight or never have to sleep?", category: "Would You Rather" },
            { question: "Would you rather have the power to stop time or travel through time?", category: "Would You Rather" },
            { question: "Would you rather only be able to whisper or only be able to shout?", category: "Would You Rather" },
            { question: "Would you rather be the funniest person in the room or the smartest?", category: "Would You Rather" },
            { question: "Would you rather have the ability to see the future or change the past?", category: "Would You Rather" },
            { question: "Would you rather be famous for doing something great or infamous for doing something bad?", category: "Would You Rather" },
            { question: "Would you rather have unlimited free food for life or unlimited free travel?", category: "Would You Rather" },
            { question: "Would you rather live without your phone or without your computer?", category: "Would You Rather" },
            { question: "Would you rather have a pet dragon or a pet unicorn?", category: "Would You Rather" },
            { question: "Would you rather be able to understand every language or be able to play every musical instrument?", category: "Would You Rather" },
            { question: "Would you rather live in a house made entirely of glass or a house with no windows?", category: "Would You Rather" },
            { question: "Would you rather live in the city or in the countryside?", category: "Would You Rather" },
            { question: "Would you rather be rich and unknown or poor and famous?", category: "Would You Rather" },
            { question: "Would you rather have the power to teleport or read minds?", category: "Would You Rather" },
            { question: "Would you rather always have to tell the truth or always lie?", category: "Would You Rather" },
            { question: "Would you rather always have perfect weather or be able to change the weather at will?", category: "Would You Rather" },
            { question: "Would you rather live without music or without movies?", category: "Would You Rather" },
            { question: "Would you rather never have to sleep again or never have to eat again?", category: "Would You Rather" },
            { question: "Would you rather never feel pain again or never feel sadness again?", category: "Would You Rather" },
            { question: "Would you rather have a personal chef or a personal trainer?", category: "Would You Rather" },
            { question: "Would you rather always have to wear winter clothes or summer clothes?", category: "Would You Rather" },
            { question: "Would you rather be able to control fire or water?", category: "Would You Rather" },
            { question: "Would you rather be able to speak every language or be able to talk to animals?", category: "Would You Rather" },
            { question: "Would you rather have free Wi-Fi wherever you go or have free coffee where/whenever you want?", category: "Would You Rather" },
            { question: "Would you rather have the ability to fly or breathe underwater?", category: "Would You Rather" },
            { question: "Would you rather always have a perfect sense of direction or never get tired?", category: "Would You Rather" },
            { question: "Would you rather have no one show up to your wedding or no one show up to your funeral?", category: "Would You Rather" },
            { question: "Would you rather be able to control your dreams or control your daydreams?", category: "Would You Rather" },
            { question: "Would you rather have the ability to see into the future or the ability to alter the past?", category: "Would You Rather" },
            { question: "Would you rather only be able to wear one color for the rest of your life or always wear a disguise?", category: "Would You Rather" },
            { question: "Would you rather be the richest person in the world but live alone, or the poorest person but have the most amazing friends?", category: "Would You Rather" },
            { question: "Would you rather live in a world where everything is free, but people never smile, or a world where everything costs money, but everyone is always happy?", category: "Would You Rather" },
            { question: "Would you rather get one million dollars but have to give it all away or get ten thousand dollars but can keep it?", category: "Would You Rather" },
            { question: "Would you rather only be able to wear hats or only be able to wear shoes?", category: "Would You Rather" },
            { question: "Would you rather be able to speak in any accent or speak in a language no one else knows?", category: "Would You Rather" },
            { question: "Would you rather eat pizza every day or never eat pizza again?", category: "Would You Rather" },
            { question: "Would you rather be an amazing cook but always eat alone, or be terrible at cooking but always share meals with others?", category: "Would You Rather" },
            { question: "Would you rather live in a world where there’s no such thing as money or live in a world where money is the only thing that matters?", category: "Would You Rather" },
            { question: "Would you rather always have to laugh at bad jokes or never be able to laugh at anything?", category: "Would You Rather" },
            { question: "Would you rather be able to talk to ghosts or be able to speak to animals?", category: "Would You Rather" },
            { question: "Would you rather have a perfect memory but never be able to forget anything, or forget everything and live in the moment?", category: "Would You Rather" },
            { question: "Would you rather live in a treehouse or in an underground bunker?", category: "Would You Rather" },
            { question: "Would you rather have super strength or super speed?", category: "Would You Rather" },
            { question: "Would you rather always have a perfect outfit or always have perfect hair?", category: "Would You Rather" },
            { question: "Would you rather be able to instantly learn any skill or be able to memorize anything you read?", category: "Would You Rather" },
            { question: "Would you rather have the ability to stop time or the ability to rewind time?", category: "Would You Rather" },
            { question: "Would you rather be able to remember every detail of your life or forget the worst moments of your life?", category: "Would You Rather" },
            { question: "Would you rather have an endless supply of your favorite food or an endless supply of your favorite drink?", category: "Would You Rather" },
            { question: "Would you rather have the power to heal others or to heal yourself?", category: "Would You Rather" },
            { question: "Would you rather travel the world for free but never come home or have a home but never leave the country?", category: "Would You Rather" },
            { question: "Would you rather be able to switch lives with anyone for a day or be able to read any book without reading it?", category: "Would You Rather" },
            { question: "Would you rather always have too much energy or always feel sleepy?", category: "Would You Rather" },
            { question: "Would you rather spend your day in a library or an amusement park?", category: "Would You Rather" },
            { question: "Would you rather be able to eat anything without gaining weight or eat whatever you want and never feel sick?", category: "Would You Rather" },
            { question: "Would you rather live without the internet or live without air conditioning?", category: "Would You Rather" },
            { question: "Would you rather be the best at one thing or mediocre at everything?", category: "Would You Rather" },
            { question: "Would you rather fight a shark with a sword or a bear with your bare hands?", category: "Would You Rather" },
            { question: "Would you rather win a million dollars or find your soulmate?", category: "Would You Rather" },
           
                
  ];
  